language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - yarn coverage
notifications:
  email: false

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"